name: Delete and upload lens

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  delete-and-upload-lens:
    uses: Gravitate-Health/reusable-workflows/.github/workflows/lenses-delete-and-upload.yaml@main
    secrets:
      FHIR_SERVER_URL: ${{ secrets.FHIR_SERVER_URL }}
      DELETE_LENS_URL: ${{ secrets.DELETE_LENS_URL }}
  delete-and-upload-lens-prod:
    uses: Gravitate-Health/reusable-workflows/.github/workflows/lenses-delete-and-upload.yaml@main
    secrets:
      FHIR_SERVER_URL: ${{ secrets.FHIR_SERVER_URL_PROD }}
      DELETE_LENS_URL: ${{ secrets.DELETE_LENS_URL_PROD }}
